uagwww_deploy:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "push"'
  image: node:15
  stage: deploy
  script:
    - npm install -g firebase-tools
    # - npm install
    # - npm run build
    - firebase deploy --token $FIREBASE_TOKEN
